### ISSUE TITLE
"character" subdir missing in links on "character/races"

### ISSUE THREAD

**Issue by nesges** [vitusventure/5thSRD#104]
on http://5thsrd.org/character/races/ 
e.g. Dragonborn links to http://5thsrd.org/races/dragonborn 
but should be http://5thsrd.org/character/races/dragonborn/

**Comment by jonbrouse** [comment]
This is due to S3/Cloudfront's lack a redirect capability. I have a Lambda function that can perform this as well as Terraform that you can use to deploy the Lambda if you're interested.  @vitusventure

**Comment by vitusventure** [comment]
It looks like this was actually a problem with having an index.md in that directory that I hand created at some point. No other nested directories have an index, so that page only existed for character/races.

That page shouldn't generally be linked to (an individual race page should be reached through the main index links, or via the navbar).

I have deleted this extraneous page here: https://github.com/vitusventure/5thSRD/commit/68e040a6bca6bbb52fec0d4b6000879e3ba4a842
