### ISSUE TITLE
Incorrect bonuses for lich, priest, and purple worm

### ISSUE THREAD

**Issue by NathanRVance** [vitusventure/5thSRD#131]
There are a few incorrect bonuses among the monsters:
- Lich should have Arcana +19, but has +18.
- Priest should have Religion +5, but has +4.
- Purple Worm should have a +14 to hit on its Bite and Tail Stinger attacks, but has +9

Thank you for this fantastic resource!

**Comment by TheYeetster1** [comment]
I'm not sure if you are looking at another reference because I have looked at the 5th handbook and have double checked that the 5thsrd is correct.

# Lich stat block:
![lichstatblock](https://user-images.githubusercontent.com/70362590/114718547-17d1fd80-9d04-11eb-94ae-cc8041ce64b4.png)
![lichstat5thsrd](https://user-images.githubusercontent.com/70362590/114718557-1a345780-9d04-11eb-9918-e0a8257e9a5d.png)

# Priest stat block:
![prieststatblock](https://user-images.githubusercontent.com/70362590/114718759-536cc780-9d04-11eb-905f-ae816741fc09.png)
![prieststatblock5thsrd](https://user-images.githubusercontent.com/70362590/114718776-5667b800-9d04-11eb-9368-9afd4cee4dea.png)

# Purple Worm stat block:
![purpleworm5thsrd](https://user-images.githubusercontent.com/70362590/114718810-5ebff300-9d04-11eb-9bc8-95d65de63cc5.png)
![purple worm5thsrd](https://user-images.githubusercontent.com/70362590/114718815-5ff12000-9d04-11eb-87dd-6d68b5d1d80c.png)

**Comment by NathanRVance** [comment]
Huh, interesting. I found it on dnd beyond ([lich](https://www.dndbeyond.com/monsters/lich), [priest](https://www.dndbeyond.com/monsters/priest), and [purple worm](https://www.dndbeyond.com/monsters/purple-worm)). I wonder if dnd beyond is wrong, of if there's some sort of errata from the print handbook (the [comments](https://www.dndbeyond.com/monsters/priest#c2) seem to suggest that this happens from time to time). It looks like roll20 agrees with you, so they must also be based on the print books.

I was tipped off to this being a potential issue when trying to deduce proficiency/expertise for monsters (assuming they follow the same rules as characters), and these seem to be the only rulebreakers (except for a few others like night hags where the proficiency bonus appears to be different for skills than attacks).

In terms of this issue, I'm closing it since you're faithful to the 5e print books, which I hadn't realized differed from other online sources. Thanks again!
